-- Recria a estrutura usada pelo aplicativo em um projeto Supabase novo.
-- Execute no SQL Editor do projeto de destino.
-- Este script cria a estrutura, mas nao copia dados, usuarios ou arquivos.

create extension if not exists pgcrypto;

create table if not exists public.perfis (
  id bigint generated by default as identity primary key,
  nickname text not null,
  connection_code text not null unique,
  onesignal_id text,
  city text,
  last_seen timestamptz,
  favorite_gifs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.perfis
  drop constraint if exists perfis_favorite_gifs_array;

alter table public.perfis
  add constraint perfis_favorite_gifs_array
  check (jsonb_typeof(favorite_gifs) = 'array');

create table if not exists public.conexoes (
  id bigint generated by default as identity primary key,
  user_code text not null,
  friend_code text not null,
  friend_name text not null default '',
  is_pinned boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_code, friend_code)
);

create table if not exists public.grupos (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  photo_url text,
  description text not null default '',
  created_by text not null,
  created_at timestamptz not null default now(),
  constraint grupos_description_length check (char_length(description) <= 500)
);

create table if not exists public.grupo_membros (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.grupos(id) on delete cascade,
  member_code text not null,
  created_at timestamptz not null default now(),
  unique (group_id, member_code)
);

create table if not exists public.mensagens (
  id bigint generated by default as identity primary key,
  sender_code text not null,
  receiver_code text not null,
  content text,
  media_url text,
  media_type text,
  read_at timestamptz,
  reply_to_id bigint references public.mensagens(id) on delete set null,
  reacoes jsonb not null default '{}'::jsonb,
  link_url text,
  preview_title text,
  preview_description text,
  preview_image_url text,
  preview_site_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.pins (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.mensagens(id) on delete cascade,
  pinned_by text not null,
  room_key text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.logs_acesso (
  id bigint generated by default as identity primary key,
  connection_code text not null,
  acessado_em timestamptz not null default now()
);

create index if not exists conexoes_user_code_idx on public.conexoes (user_code);
create index if not exists grupo_membros_member_code_idx on public.grupo_membros (member_code);
create index if not exists grupo_membros_group_id_idx on public.grupo_membros (group_id);
create index if not exists mensagens_sender_receiver_idx on public.mensagens (sender_code, receiver_code, created_at desc);
create index if not exists mensagens_receiver_code_idx on public.mensagens (receiver_code, created_at desc);
create index if not exists mensagens_link_url_idx on public.mensagens (link_url) where link_url is not null;
create index if not exists pins_room_key_idx on public.pins (room_key);
create index if not exists logs_acesso_code_time_idx on public.logs_acesso (connection_code, acessado_em desc);

-- O aplicativo usa o cliente anon e nao Supabase Auth para identificar perfis.
-- RLS deve permanecer desativado para estas tabelas, como no projeto atual.
alter table public.perfis disable row level security;
alter table public.conexoes disable row level security;
alter table public.grupos disable row level security;
alter table public.grupo_membros disable row level security;
alter table public.mensagens disable row level security;
alter table public.pins disable row level security;
alter table public.logs_acesso disable row level security;

insert into storage.buckets (id, name, public)
values ('chat-media', 'chat-media', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists chat_media_anon_select on storage.objects;
drop policy if exists chat_media_anon_insert on storage.objects;
drop policy if exists chat_media_anon_update on storage.objects;
drop policy if exists chat_media_anon_delete on storage.objects;

create policy chat_media_anon_select on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'chat-media');

create policy chat_media_anon_insert on storage.objects
  for insert to anon, authenticated
  with check (bucket_id = 'chat-media');

create policy chat_media_anon_update on storage.objects
  for update to anon, authenticated
  using (bucket_id = 'chat-media')
  with check (bucket_id = 'chat-media');

create policy chat_media_anon_delete on storage.objects
  for delete to anon, authenticated
  using (bucket_id = 'chat-media');

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'mensagens'
  ) then
    alter publication supabase_realtime add table public.mensagens;
  end if;
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'perfis'
  ) then
    alter publication supabase_realtime add table public.perfis;
  end if;
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'grupo_membros'
  ) then
    alter publication supabase_realtime add table public.grupo_membros;
  end if;
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'grupos'
  ) then
    alter publication supabase_realtime add table public.grupos;
  end if;
end $$;